[package]
name = "archiver"
version = "0.1.0"
edition = "2021"

[dependencies]
stateful = { git = "https://github.com/limads/stateful.git" }
gtk4 = "0.4"
chrono = "0.4.19"
notify = "4.0.17"
serde = { version="1.0.130", features=["derive"] }
sourceview5 = { version = "0.4" }
serde_json = "1.0.68"
